[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "renkon"
dynamic = ["version"]
description = 'Robust likely invariant analysis over columnar data'
readme = "README.md"
requires-python = ">=3.12"
license = "BSD-3-Clause"
keywords = []
authors = [
    { name = "Dylan Lukes", email = "lukes.dylan@gmail.com" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = [
    # Data Processing
    "aiosql", # SQL
    "numpy", # Numerical computing
    "scikit-learn", # Machine learning
    "scipy", # Scientific computing
    "polars", # Data frames
    "pandas", # Data frames (not used, but needed for stubs in typings to not be Unknown)
    "pyarrow", # Columnar data format
    "pydantic", # Data validation

    # Infrastructure
    "loguru", # Logging
    "dacite", # Dataclass deserialization

    # Interface
    "click", # CLI
    "rich", # Pretty console output
]

optional-dependencies.dev = [
    "pyright",
    "pytest"
]

[project.urls]
Documentation = "https://github.com/DylanLukes/renkon#readme"
Issues = "https://github.com/DylanLukes/renkon/issues"
Source = "https://github.com/DylanLukes/renkon"

[project.scripts]
renkon = "renkon.cli:cli"

# Tool Configurations
# ===================

# Hatch
# -----

[tool.hatch.version]
path = "src/renkon/__about__.py"

[tool.hatch.envs.default]
dependencies = [
    "coverage[toml]>=6.5",
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "pytest-randomly",
    "pytest-rerunfailures",
    "pytest-xdist"
]

[tool.hatch.envs.default.scripts]
test = "pytest {args:tests}"
test-cov = "coverage run -m pytest {args:tests}"
cov-report = [
    "- coverage combine",
    "coverage report",
]
cov = [
    "test-cov",
    "cov-report",
]

[[tool.hatch.envs.all.matrix]]
python = ["3.12"]

[tool.hatch.envs.hatch-static-analysis]
config-path = "ruff_defaults.toml"

[tool.hatch.envs.types]
dependencies = [
  "pyright",
]

[tool.hatch.envs.types.scripts]
check = "pyright {args:src/renkon tests/}"

# Pyright
# -------

[tool.pyright]
include = ["./src", "./tests"]
stubPath = "./typings/stubs/"

typeCheckingMode = "strict"
reportMissingImports = true
reportMissingTypeStubs = true

pythonVersion = "3.12"

# Ruff
# ----

[tool.ruff]
extend = "ruff_defaults.toml"
exclude = [".hatch", "scripts", "typings"]

[tool.ruff.isort]
known-first-party = ["renkon"]

[tool.ruff.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.per-file-ignores]
# Tests can use magic values, assertions, and relative imports
"tests/**/*" = ["PLR2004", "S101", "TID252"]

# Coverage
# --------

[tool.coverage.run]
source_pkgs = ["renkon", "tests"]
branch = true
parallel = true
omit = [
    "src/renkon/__about__.py",
]

[tool.coverage.paths]
hatch_demo = ["src/renkon", "*/renkon/src/renkon"]
tests = ["tests", "*/renkon/tests"]

[tool.coverage.report]
exclude_lines = [
    "no cov",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
]
